### ISSUE TITLE
运行脚本,报找不到脚本命令

### ISSUE THREAD

**Issue by xueqiulou** [carya/Util#1]
from: can't read /var/mail/optparse
/Users/apple/Desktop/autobuild.py: line 2: import: command not found
/Users/apple/Desktop/autobuild.py: line 3: import: command not found
/Users/apple/Desktop/autobuild.py: line 6: CODE_SIGN_IDENTITY: command not found...
这是什么原因?

**Comment by wangdxnum1** [comment]
一样的问题，求指导

**Comment by carya** [comment]
@xueqiulou , @wangdxnum1 , 你们重新下载脚本试一下呢，可能是python的环境没设置好
