### ISSUE TITLE
运行环境的问题

### ISSUE THREAD

**Issue by fallenk** [carya/Util#3]
命令行运行 ./autobuild.py -w yourname.xcworkspace -s schemename -o ~/Desktop/yourname.ipa
出现以下问题
File "./autobuild.py", line 9, in <module>
import requests
ImportError: No module named requests

**Comment by iosbin** [comment]
命令行运行 ./autobuild.py -w yourname.xcworkspace -s schemename -o ~/Desktop/yourname.ipa
出现以下问题
File "./autobuild.py", line 9, in 
import requests
ImportError: No module named requests

Python 2.7.10

**Comment by carya** [comment]
使用 `$ sudo pip install requests`或者`sudo easy_install -U requests` 安装 *request module*。
