### ISSUE TITLE
这个怎么解决？

### ISSUE THREAD

**Issue by qikai521** [carya/Util#4]
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 3.)

Error Domain=IDEDistributionErrorDomain Code=3 "(null)" UserInfo={IDEDistributionErrorSigningIdentityToItemToUnderlyingErrorKey={
    "<DVTSigningCertificate: 0x7fcbe59bf0e0; name='iPhone Distribution: Stone (Qingdao) Network Software Technology Co., Ltd. (UG42VAE5R4)', hash='05C57B35EF8CE3CFE112BEBA9260F39C805A4F52', serialNumber='53DA8EF404276A71', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2017-01-03 01:42:06 +0000''>" =     {
        "<IDEDistributionItem: 0x7fcbe37c5490 'com.HaiYang.ORGZhu' '<DVTFilePath:0x7fcbe5d8fdf0:'/Users/qikai/desktop/trydemo/TryDemo.xcarchive/Products/Applications/TryDemo.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=10 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=No valid 'ad-hoc' profiles were found., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fcbe59bc8f0; portalTeamID='UG42VAE5R4', usingTeamBasedSigning='NO', bundleIdentifier='com.HaiYang.ORGZhu', targetName='(null)', provisioningProfilePurpose='2', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"UG42VAE5R4.com.HaiYang.ORGZhu\";\n    \"keychain-access-groups\" =     (\n        \"UG42VAE5R4.com.HaiYang.ORGZhu\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
    };
}}

** EXPORT FAILED **

export TryDemo failed
cleaned archiveFile: /Users/qikai/desktop/trydemo/TryDemo.xcarchive

**Comment by carya** [comment]
>{NSLocalizedRecoverySuggestion=No valid 'ad-hoc' profiles were found., NSLocalizedDescription=No matching provisioning profiles found,

你的电脑上没有找到对应的provisioning profiles文件
